# Example config file for 1-step training (local Windows, GPU)
data_dir: "E:/warm rain/warm-rain-emulator/data_mini"
tot_len: 719

sim_num: 25
avg_dataloader: True
single_sim_num: null
moment_scheme: 2
batch_size: 32                               # smoke for small dataset, then rise to 128/256

beta: 0.35
learning_rate: 1e-4

act: torch.nn.ReLU()
loss_func: null

n_layers: 3
ns: 200

depth: 9
p: 0.25
norm: Standard_Norm
inputs_mean: null
inputs_std: null
loss_absolute: True
mass_cons_moments: True
mass_cons_updates: True
hard_constraints_moments: False
hard_constraints_updates: False
multi_step: False
step_size: 1
max_epochs: 2                                # change back to 500 later
use_batch_norm: False
use_dropout: False

save_dir: "E:/warm rain/warm-rain-emulator/outputs/run_main" 
pretrained_dir: null
ro_norm: False
